name: codegen17
channels:
  - sympy
  - symengine
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - notebook
  - nbconvert
  - numpy
  - matplotlib
  - scipy
  - cython
  - theano
  - pip:
      - https://github.com/sympy/sympy/archive/7efbee85cf49d767a11de8344b2b99b2b2460769.tar.gz
  - sundials
  - python-symengine
  - numba
  - scipy2017codegen
